### ISSUE TITLE
Clearly indicate the charts are for a selected polygon not a pixel

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#101]
One user found it unclear if the charts refer to the trends for one pixel or for the polygon.  To increase the usability, the user suggested:
1. Adding the pink/purple color to the legend with something like "Selected iGDE for displaying chart data"
2. Using the pink/purple color in the chart panel to tie the two things together- Perhaps use that color for the text  "Groundwater Dependent Ecosystem" in the title in the side panel

**Comment by nathanielrindlaub** [comment]
I don't really want to hack the Esri legend widget any further than I already have, and I don't think making the text or title of the sidebar pink will help clarify this user's confusion. Now that the GDE polygons are hidden by default, but the highlighted polygon appears when you click on the raster, it might be more clear that the thing you're selecting is the GDE, rather than a pixel.

Closing this out for now but feel free to re-open if other users struggle with this anyone has other ideas for solving it.
