### ISSUE TITLE
Use baselayer icons

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#105]
Consider automatically switching the basemap as the user zooms in- make the switch to the aerial base when the wells and GDEs appear.

Also, lets use the basemap with the reference data- road names, county lines, etc.

**Comment by nathanielrindlaub** [comment]
Eating my words... I know I previously had pushed back on the auto-basemap-switching idea because I had never really seen a web map do that and thought it might be unexpected to users, but last night I was on Zillow and they do that exact same thing! When you zoom in super tight it turns to the labeled satellite basemap - and I think it works well and did not seem like jarring or unexpected behavior. I probably wouldn't have even noticed had we not talked about doing it for GDE. So I implemented it and I think it works nicely. 

Current scale threshold that the basemap gets toggled at is 100000. Happy to move that up or down. You can also still manually toggle the basemap using the original button. I probably will not switch the basemap toggle button icon as we had discussed doing a couple weeks ago now if that's ok.

**Comment by nathanielrindlaub** [comment]
also not live yet. Holding off till Kirk gives the OK.

**Comment by kklausmeyer** [comment]
Just tested it and I like it!  Score for Zillow!
