### ISSUE TITLE
Make links in upper right of page more clear

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#106]
Change the term "Science" to "Methology" throghout the page.  Also, provide underlines or some way to indicate they are clickable.  This wasn't clear to users.

**Comment by nathanielrindlaub** [comment]
Done bc4f1d4 . I did a handful of styling updates, including updates to the nav-bar links, which I think make the app look a bit more clean & modern. The nav bar links don't have underlines like a hyperlink, but as I surveyed other websites that's actually a very rare treatment for nav menu links. Most websites reserve some kind of underline or accent styling to indicate which link is currently selected, rather than to make it clear that they're all links. Hopefully what I have now is more intuitive though.
