### ISSUE TITLE
Tell users to click on GDEs with a hint

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#120]
Several users have requested a hint to indicate that you can click on the GDE areas to see a chart.  Here is one idea, but a simple hint prompting a click would be fine:
From Melissa Rhode:
"Some other feedback I heard from Santa Cruz Mid-County: When first visiting the site and after zooming in to an area of interest, it isn’t initially apparent that the polygons can be clicked on and that right panel pops up with graphs.  One thought I had to resolve this is as a default we could have the side bar appear upon zooming in to an area of interest, with some text instructing the viewer to click on a polygon to populate the graphs below."

**Comment by nathanielrindlaub** [comment]
I changed the little UX hint in the lower left hand corner to change depending on zoom level. If you're zoomed out beyond the GDE polygon layer's visibility range, it says "Hint: zoom in to view GDEs". If you zoom in, it says "Hint: click on a GDE to view its trend data". 

Happy to modify that text if you have edits. Otherwise I think we can close this out.

**Comment by kklausmeyer** [comment]
Hi Natty-  this is great, but we need some new labels in the legend so the hint makes sense.  I will create a new issue with the suggested changes so people know what a GDE is based on the legend.
