### ISSUE TITLE
Add popup or label to GW basins

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#148]
Hi Natty-  Can you add a pop up when you click on a GW basin?  I would like to see the Basin Name, Sub Basin Name, and the Sub Basin Number.  

Alternatively, a label on the map with the basin name and sub-basin name would be great.

**Comment by nathanielrindlaub** [comment]
Hey Kirk, I'm thinking I'll open up the side bar when a user selects a GWB to keep the UX consent (click a feature, info gets displayed in the sidebar). For the sidebar content for groundwater basins, we have a lot of room so we could display any of the attributes on [this endpoint](https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_B118_CA_GroundwaterBasins/FeatureServer/0). Do you have thoughts on what order we should display them in? 

Also, seems like being able to search by GWB would be really useful. What attributes would people be searching by? What is kind of the primary attribute for identifying a GWB (I'd assume Basin_Name or Basin_Number)?

**Comment by nathanielrindlaub** [comment]
@kklausmeyer - I just made some guesses and deployed and update with the groundwater basin changes. Let me know if you'd like anything to be different.

Also (maybe for v. 2.0) would be cool to do some basin-level roll-ups of GDE data and display them in the groundwater basin sidebar. Easy ones would be like counting the number of GDEs in each basin or the total GDE area... more involved might be plotting average NDVI, NDMI, and Precip trends for all GDEs in that basin. Might be too many requests to our API though if there are tons of GDEs in each basin, so that one might be better calculated once and baked into a custom GW basin endpoint... just thinking out loud.

Anyhow. Please review and feel free to close this out if it's satisfactory.

**Comment by kklausmeyer** [comment]
Looks great!  I'll add your other ideas to a new issue under the v2 milestone.  I don't want to lose your thinking.
